apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9999
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9999
  selector:
    app: app2
