name: API to (1) Dev

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - run: echo testing

      - name: Repository dispatch test
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          event-type: trigger-web-dev
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

