name: Cypress Testing

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  workflow_dispatch:

jobs:
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show ENV
        run: echo "$GITHUB_CONTEXT"

      #- name: Cypress testing
      #  uses: cypress-io/github-action@v2
      #  with:
      #    build: npm i -D cypress
      #    headless: true
      #    working-directory: ./web

      #- name: Archive files
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: cypress video
      #    path: web/cypress/videos/

      - name: Link to workflow
        run: echo "There was an error in the Cypress test(s) for the registry app during the ${{ github.workflow }} workflow.  View the output and download test output files here: https://github.com/IanKWatts/test10/actions/runs/${{ github.run_id }}"

      #- name: RocketChat notification
      #  run: curl -X POST -H 'Content-Type: application/json' --data '{"text":"There was an error in the Cypress test(s) for the registry app during the..."}' "${{ secrets.ROCKET_CHAT_HOOK_URL }}"

