name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cypress testing
        uses: cypress-io/github-action@v2
        with:
          build: npm i -D cypress
          headless: true
          working-directory: ./web

      - name: Show cypress files
        run: ls -lR .

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: cypress video
          path: web/cypress/videos/test1.js.mp4

