name: Manual Action Test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start build
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          parameters: '{ "apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true" }'
          cmd: |
            'version'
            'start-build test10 --follow -n iankwatts-tools'
            'tag -n iankwatts-tools test10:latest test10:$(oc get -o=jsonpath="{.spec.revision.git.commit}" build test10-$(oc get -o=jsonpath="{.status.lastVersion}" buildconfig test10)) test10:test'
