name: Action on release publish

on:
  release:
    types: [published, created, released]

jobs:
  do_on_publish:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_VERSION: 7.1.5
    steps:
      - name: Install to Prod
        run: echo "Installing Artifactory version ${{ env.ARTIFACTORY_VERSION }} to Prod..."

