name: Testing paths-filter

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  pull_request:
    types: [ opened ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug1
        run: echo $GITHUB_CONTEXT

      - name: debug2
        run: echo ${{ env.github }}

