name: Testing paths-filter

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "db/**"
      - "web/**"
  workflow_dispatch:

jobs:
  check_for_component_changes:
    runs-on: ubuntu-latest
    outputs:
      db: ${{ steps.filter.outputs.db }}
      api: ${{ steps.filter.outputs.api }}
      web: ${{ steps.filter.outputs.web }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          db:
            - 'db/**'
          api:
            - 'api/**'
          web:
            - 'web/**'
    - run: echo "env.GITHUB_CONTEXT: $GITHUB_CONTEXT"

  db_test:
    needs: check_for_component_changes
    runs-on: ubuntu-latest
    steps:
      - name: debug
        if: ${{ needs.check_for_component_changes.outputs.db == 'true' }}
        run: echo db_test

  api_test:
    needs: [db_test]
    if: ${{ needs.check_for_component_changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo api_test

  api_build:
    needs: [api_test]
    if: ${{ needs.check_for_component_changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo api_test

  web_test:
    needs: [db_test]
    if: ${{ needs.check_for_component_changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo web_test

  web_build:
    needs: [web_test]
    if: ${{ needs.check_for_component_changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo web_test

